### ISSUE TITLE
jio.summary.extract_summary报错

### ISSUE THREAD

**Issue by tucker666** [dongrixinyu/JioNLP#10]
Traceback (most recent call last):
  File "split_test.py", line 59, in <module>
  File "D:\software\anaconda\envs\torch13\lib\site-packages\jionlp\algorithm\summary\extract_summary.py", line 140, in __call__
    sen_segs[3] = len([w for w in sen_segs_weights if w != 0]) / len(sen_segs_weights)
ZeroDivisionError: division by zero

**Comment by dongrixinyu** [comment]
输入是什么呢？

**Comment by tucker666** [comment]
自9月开始，国债期货开始了一轮回调行情，主要逻辑在于全球风险因素出现缓和。进入10月，英国脱欧事件反复，避险情绪的上升仍未能带动国债期货反弹，资金面和基本面预期逐渐成为主导因素：节后资金面整体处于偏紧状态，基本面预期回暖，造成国债期货价格的持续下行。当前中债国债收益率分别在3.08%和3.30%附近，两者利差较10月初略有扩大。 资金面难有明显宽松 本周中国人民银行再度暂停逆回购操作，周二到期2500亿元与周三到期2000亿元均未对冲续作，尽管与月末财政支出增加有关，但也表明央行态度仍然偏谨慎。回顾10月份以来央行操作，在公开市场投放方面始终相对谨慎，截至目前投放逆回购6200亿元与MLF2000亿元，到期回笼8500亿元，合计到期净回笼300亿元。但今年以来各季度初投放的TML始终未能出现，9月份降准也以对冲资金缺口为主。 四季度货币宽松仍存在两大压力。一方面在于猪价持续上行推升通胀预期，10月第四周，22省市猪肉均价继续上升至56.02元/千克，较前一周的45.51元/千克环比上涨23.09%，也同时带动食品类价格增速全线上扬。预计通胀上行压力将持续至2020年一季度，因此短期内货币宽松的可能性较低；另一方面在于全球经济处于下行周期，政策重心转向LPR利率改革等疏通货币传导渠道的中长期调整，守住降息空间尤为重要，因此我国央行操作上也将持续偏谨慎，货币投放方面以微调为主。 基本面预期改善？债市承压 本周将公布10月份PMI数据，尽管整体看数据仍有下行可能，但部分数据出现边际改善，市场对于基本面改善的预期将持续作用于债市。9月份制造业企业投资增速尽管略有下行，但分化较为明显，下游终端需求制造业投资增速下行速度较快，中游制造业投资增速开始回暖，其中作为制造业投资增速的先行指标：设备制造业投资增速出现企稳反弹迹象。进入10月份后，高频数据如发电耗煤量与高炉开工率较三季度均有持续改善，表明9月份的工业数据边际改善并不单纯受到台风后复工的影响，PMI数据同样显示工业企业去库存已接近尾声，后市随着工业企业的开工、库存周期复苏，工业品价格有望重归上行，带动PPI回归正增长。 除去工业数据外，地产投资增速持平于高位、基建投资增速温和回暖等因素也为基本面预期提供一定支撑，而后市受到双十一、双十二等电商促销的影响，消费数据将有边际改善。整体看，经济基本面边际改善预期自8月末开始发酵，当前仍仅体现在部分数据上，后续在政策支持、工业周期回升等因素作用下将进一步验证，对利率水平构成持续压力。 综上，预计在经济基本面持续改善、货币政策难有明显宽松的背景下国债收益率有小幅走高可能，且这一过程持续时间仍较长，即便存在美联储议息会议、英国脱欧等风险因素的短期干扰，债市仍难以形成有效反弹趋势。因此，国债期货尚无明显反弹动力，抄底仍需谨慎。

**Comment by tucker666** [comment]
链接：https://pan.baidu.com/s/1ndoXJjP5gKE5ci5sLkXQaQ 
提取码：wgva 
文件里的会报错，放到github评论上的没问题了

**Comment by tucker666** [comment]
没问题了，需要strip一下

**Comment by dongrixinyu** [comment]
已修复
