### ISSUE TITLE
gevent启动多worker时报错

### ISSUE THREAD

**Issue by micrazy** [dongrixinyu/JioNLP#102]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.8
- jionlp 版本: 1.4.28

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
app = Flask(__name__)
def __somefunc:
    call jionlp

http_server = WSGIServer(('0.0.0.0', 8018), app)
http_server.serve_forever()

bash：
gunicorn main:app --worker-class gevent -b 0.0.0.0:8018 -w 4
```

3. 调用报错日志如下(Log):
```
xxxxxxxxxxxx
e.g.
FileExistsError: [Errno 17] File exists: '/root/.jiojio/jiojio_logs'
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online use.
# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
During handling of the above exception, another exception occurred:
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**期望行为(Expectation)**
gunicorn多worker正常启动
> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)


**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
你的问题应该是多进程争读 jiojio 日志造成的。jionlp 也存在这个问题，可以参考这个把日志关闭：[日志助手](https://github.com/dongrixinyu/JioNLP/wiki/%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99-%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3#user-content-%E6%97%A5%E5%BF%97%E5%A4%84%E7%90%86%E8%AE%BE%E7%BD%AE%E5%87%BD%E6%95%B0)

**Comment by dongrixinyu** [comment]
![image](https://user-images.githubusercontent.com/27001062/209523549-b7baf979-4ae4-48d3-b0de-c17324b392c4.png)

**Comment by wAnFen1017** [comment]
设置后仍然会报错，在导入jionlp时就已经抛出异常了
