### ISSUE TITLE
请问extract_keyphrase是否支持添加自定义词典？

### ISSUE THREAD

**Issue by houyongsheng** [dongrixinyu/JioNLP#108]
**咨询的功能模块**
- jio.keyphrase.extract_keyphrase

**咨询的具体内容和问题**
- 请问extract_keyphrase是否支持添加自定义词典？谢谢！

**Comment by houyongsheng** [comment]
有尝试在 jiojio/__init__.py里指定cws_user_dict路径，但好像没有效果。

**Comment by dongrixinyu** [comment]
看[源码加注释](https://github.com/dongrixinyu/JioNLP/blob/master/jionlp/algorithm/keyphrase/extract_keyphrase.py)
