### ISSUE TITLE
地址解析错误，香港的识别到甘肃

### ISSUE THREAD

**Issue by XavierWonderful** [dongrixinyu/JioNLP#110]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**
{
    "province":"甘肃省",
    "city":"天水市",
    "county":"清水县",
    "detail":"湾畔香港科技大学",
    "full_location":"甘肃省天水市清水县湾畔香港科技大学",
    "orig_location":"香港特别行政区西贡区清水湾畔香港科技大学",
    "offset_index":10,
    "contained_location":"清水湾畔香港科技大学"
}
> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):1.4.30
- python 版本: (通过 `python` 可查)
- jionlp 版本: (通过 `jionlp.__version__` 可查)

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
res = jio.parse_time('XXXX')
print(res)
```

3. 调用报错日志如下(Log):
```
xxxxxxxxxxxx
e.g.
trackback: XXXXXX
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

**Comment by XavierWonderful** [comment]
{
    "province":"四川省",
    "city":"甘孜藏族自治州",
    "county":"九龙县",
    "detail":"半岛清水湾香港科技大学",
    "full_location":"四川省甘孜藏族自治州九龙县半岛清水湾香港科技大学",
    "orig_location":"香港九龙半岛清水湾香港科技大学",
    "offset_index":2,
    "contained_location":"九龙半岛清水湾香港科技大学"
}

**Comment by dongrixinyu** [comment]
已修复
