### ISSUE TITLE
西安被优先匹配至吉林省辽源市的西安区

### ISSUE THREAD

**Issue by fireindark707** [dongrixinyu/JioNLP#112]
**描述(Description)**

> 西安被优先匹配至吉林省辽源市的西安区

1. 版本(Version):
- python 版本: 3.9
- jionlp 版本: 1.4.33

2. jionlp的调用代码与输入文本(Code & Text):
```
西安一艺术学习中心突然关门
```

**期望行为(Expectation)**

> 返回陕西省西安市

**Comment by dongrixinyu** [comment]
你用最新版试试，这个是个老问题早解决过了。
