### ISSUE TITLE
时间标准化 日期中下旬解析

### ISSUE THREAD

**Issue by mzhan818** [dongrixinyu/JioNLP#114]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: (通过 `python` 可查)
- jionlp 版本: (通过 `jionlp.__version__` 可查)

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
res = jio.parse_time('XXXX')
print(res)
```

3. 调用报错日志如下(Log):
```
xxxxxxxxxxxx
e.g.
trackback: XXXXXX
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

这串代码中，是不是下旬应该first_day = 21 而不是11？

elif '下旬' in blur_day_string:
                first_day = 11
                second_day = -1

**Comment by dongrixinyu** [comment]
是的，感谢

**Comment by dongrixinyu** [comment]
已经更新到 git 上了，可以试一下可否成功安装并调用

**Comment by mzhan818** [comment]
> 
卸载旧版本 重新pip安装，该bug还是存在，没有修复的，大佬看下
