### ISSUE TITLE
自动补全地址时，原文本中错误行政级别不会删除，导致结果多字

### ISSUE THREAD

**Issue by Leeedaye** [dongrixinyu/JioNLP#116]
**描述(Description)**

> 调用jio.parse_location()时，如果输入文本中有错误的行政级别，函数不会删除，导致full_location中会多字。如下返回后full_location中海门区返回为海门区市，多了一个市字。

1. 版本(Version):
- python 版本: 3.10
- jionlp 版本: 1.4.33

2. jionlp的调用代码与输入文本(Code & Text):
# -*- coding:utf-8 -*-
import jionlp  as jio

def add_process(address):
    full_result=jio.parse_location(address)
    result=jio.parse_location(full_result['full_location'],town_village=True)
    add_res = []
    add_res.append(result['province'])
    add_res.append(result['city'])
    add_res.append(result['county'])
    add_res.append(result['town'])
    add_res.append(result['village'])
    full_location = full_result['full_location'].replace("。","")
    add_res.append(full_location)
    return add_res

if __name__ == "__main__":
    add = '江苏省海门市余东镇木桩港村二十三组'
    print(add_process(add))

**期望行为(Expectation)**

返回：['江苏省', '南通市', '海门区', '余东镇', '木桩港村', '江苏省南通市海门区市余东镇木桩港村二十三组']
期望返回：['江苏省', '南通市', '海门区', '余东镇', '木桩港村', '江苏省南通市海门区余东镇木桩港村二十三组']

**Comment by dongrixinyu** [comment]
我很早就知道这个bug。所以`full_loc` 实际上并非准确的地址结果。困难点在于，依赖上下文。依赖上下文的问题还是用模型来处理比较好。很难设计出泛化OK  的 规则逻辑来做这个工作。
