### ISSUE TITLE
[功能请求]对于使用逗号分隔的语句，整句文本解析日期。

### ISSUE THREAD

**Issue by cx4** [dongrixinyu/JioNLP#118]
"事实和理由：原、被告2003年经人介绍相识、相恋，于同年6月18日登记结婚。"
使用解析，“同年” 识别为2023年，能否将整句，解析的时间为 2003年6月18日。

**Comment by uyoin** [comment]
jio.parse_time函数第二个参数你把系统时间作为basetime弄进去好像就可以了

**Comment by dongrixinyu** [comment]
工具是基于符号和逻辑解析的，所以优点是准确，缺点是泛化不足，基于句子是做不到的。可以先解析第一个时间2013年，然后以 2013年作为time_base 解析第二个时间。前提是句子表达含义在同一时间语境下。这个可以自己写个简单的逻辑做hack，如果情况太过复杂，可以做一个模型进行判断
