### ISSUE TITLE
时间标准化 后期是否考虑支持如，Q1季度，前两个Q等相关需求呢？

### ISSUE THREAD

**Issue by mzhan818** [dongrixinyu/JioNLP#119]
**描述该功能的用处，可以提供相关资料描述该功能**

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
Q1 季度这种可以支持，前两个Q这种太依赖上下文了

**Comment by dongrixinyu** [comment]
Q1 已支持
