### ISSUE TITLE
[技术咨询]如何屏蔽掉 Jio自带的打印信息？

### ISSUE THREAD

**Issue by mzhan818** [dongrixinyu/JioNLP#123]
-------------------------------------------------
强迫症，如何屏蔽掉 这两行打印？
# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.

可以进入源码屏蔽，但是每次安装之后都得再操作一遍
明白作者为了推广，但是还想屏蔽了。不开心

**Comment by dongrixinyu** [comment]
你直接源码里搜一下这两行，直接删掉就行
