### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by zsn1998** [dongrixinyu/JioNLP#124]
项目引入这个包后一运行就报错
PermissionError: [Errno 13] Permission denied: '/data/app/virtualenv/python3.6/lib/python3.6/site-packages/jionlp/dictionary/chinese_char_dictionary.txt'
然后去看了下这个目录，发现压缩包没有解压

**Comment by dongrixinyu** [comment]
参照项目安装教程步骤来
