### ISSUE TITLE
国内行政区划变动未识别的问题

### ISSUE THREAD

**Issue by chrisforU** [dongrixinyu/JioNLP#126]
1. 地级市更名问题
raw_addres = "湖北省襄樊市"
jio.parse_location(raw_addres,change2new=True) 解析出的结果不能识别地级市，2010年12月9日，襄樊市正式更名为襄阳市。

2. 广西省的柳州和南宁有歧义。
raw_addres = "柳州地区忻城县"在解析时，不会自动转化为来宾市，而是解析为柳州市。
2002年，撤销柳州地区，设来宾市，来宾市辖原柳州地区忻城、象州、武宣、金秀4县和兴宾区，代管合山市。原柳州地区的鹿寨、融安、融水、三江4个县划归柳州市管辖。
2002年，撤销南宁地区，设立地级崇左市，原南宁地区的横县、马山县、宾阳县、隆安县、上林县划归南宁市管辖。

想咨询一下，国内行政区划变动的旧地址识别，目前是包括了哪些年份的行政区划变动呢？谢谢。

**Comment by dongrixinyu** [comment]
只包含了大约2016年以后的变更，这个可以抽空更新一下
