### ISSUE TITLE
[技术咨询]执行速度很慢

### ISSUE THREAD

**Issue by Junesui** [dongrixinyu/JioNLP#129]
### 首先感谢开源。

**咨询的功能模块**
关键短语提取

**咨询的具体内容和问题**
执行时间很长

如图所示，执行这个代码到输出结果，需要十几秒。这是正常情况吗吗
![image](https://user-images.githubusercontent.com/53398033/230807568-f4228a23-50b4-402a-bcb3-2c5b5fb2d64b.png)

**Comment by Junesui** [comment]
【关键短语提取】之前，添加个【抽取式文本摘要】，这个程序执行完就需要50秒。

**Comment by Junesui** [comment]
http://www.jionlp.com/jionlp_online/extract_keyphrase

在线版却很快，这是为什么。
期待回复

**Comment by dongrixinyu** [comment]
默认初始化没暴露出来。程序里第二次执行试试。
