### ISSUE TITLE
[BUG] clean_text(, delete_prefix=True)

### ISSUE THREAD

**Issue by Yulv-git** [dongrixinyu/JioNLP#132]
**描述(Description)**

1. 版本(Version):
- python 版本: 3.7.12
- jionlp 版本: 1.4.37

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio

# 异常示例
res = jio.clean_text('课程，联系电话：13302130583', delete_prefix=True)
print(res)  # ''

# 我想上述示例应该输出的是：'课程，'，而不是 ''
```

**Comment by Yulv-git** [comment]
`
import jionlp as jio

# 以下例子也是异常输出为空 ‘’
res = jio.clean_text('请发简历至dongyu@163.com。', delete_prefix=True)
res = jio.clean_text('请发简历至邮箱：dongyu@163.com。', delete_prefix=True)
res = jio.clean_text('请发简历至邮箱：dongyu@163.com。', delete_prefix=True)
`

**Comment by dongrixinyu** [comment]
非常感谢！
