### ISSUE TITLE
[技术咨询]LLM测试集是只有62条吗？

### ISSUE THREAD

**Issue by enze5088** [dongrixinyu/JioNLP#141]
希望能增加更多关于LLM测试集的信息，如数据量之类的，主观题测评标准等。

**Comment by dongrixinyu** [comment]
[说明文档](https://github.com/dongrixinyu/JioNLP/wiki/LLM%E8%AF%84%E6%B5%8B%E6%95%B0%E6%8D%AE%E9%9B%86)
