### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by r2dh4t** [dongrixinyu/JioNLP#145]
令整个程序停顿（原因没细看）

1. 版本(Version):
- python 版本: 3.7.7
- jionlp 版本: 1.4.35

2. jionlp的调用代码与输入文本(Code & Text):
```
text = 'xxx@xxx.COM..................................................'
text = jionlp.clean_text(text)
print(text)
```

自己写模块先将重复N次以上的相同字符串替换后再放入jionlp就OK了。作者视情况更新吧~

**Comment by dongrixinyu** [comment]
已修复
