### ISSUE TITLE
多进程import jionlp as jio抛出异常FileExistsError: [Errno 17] File exists: '/root/.jionlp_logs'

### ISSUE THREAD

**Issue by smallmocha** [dongrixinyu/JioNLP#146]
https://github.com/dongrixinyu/JioNLP/wiki/%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99-%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3
此方法设置jio.logging = jio.set_logger(level="WARN", log_dir_name=None)只能解决后续日志写入文件的问题，
并没有解决多线程 多进程import jionlp as jio时抛出异常的问题，实际导致本次import时失败的，是否可默认不把日志输出到文件中？

**Comment by wAnFen1017** [comment]
作者大大，能否在未来的版本默认关闭日志呢，有需要的用户可以自己手动开启

**Comment by LBYPatrick** [comment]
我只想说 多进程的情况下logging根本关不掉 而且会报一些我们完全不需要看的错误，比如这种：

```
[2023-07-23 09:38:28,307] [   ERROR] time_parser.py:1261 - Traceback (most recent call last):
  File "/root/autodl-tmp/conda-envs/langchain-test/lib/python3.10/site-packages/jionlp/gadget/time_parser.py", line 981, in parse_time_span_point
    first_full_time_handler, _, _, blur_time = self.parse_time_point(
  File "/root/autodl-tmp/conda-envs/langchain-test/lib/python3.10/site-packages/jionlp/gadget/time_parser.py", line 1526, in parse_time_point
    raise ValueError('## exception string `{}`.'.format(time_string))
ValueError: ## exception string `2`.
```

这个也是jioNLP用logger打出来的东西，因为我把Logger全局关闭后（我们项目内处理Exception时打印日志不使用logger库）这种东西就没了

另外，我也尝试用了作者提供的关闭日志方法，如下（这段代码出现在了每个用到了jionlp的文件开头）

```python
import jionlp as jio
import jiojio

jio.set_logger(None)
jiojio.set_logger(None)
```

根本没有效果，所以上面的那条错误信息还是在执行了上面的代码后出现的
@dongrixinyu

**Comment by smallmocha** [comment]
我只能说作者完全get不到点，没有动手实践多进程。建议大家在主进程先import jionlp绕过这个bug

**Comment by LBYPatrick** [comment]
> 我只能说作者完全get不到点，没有动手实践多进程。建议大家在主进程先import jionlp绕过这个bug

@smallmocha 其实这样也还是根治不了问题，因为很多人都在用asyncio或者间接在用基于asyncio的库，而multiprocessing的fork(copy-on-write)进程方法跟asyncio是有冲突的，于是在大多数情况下会spawn一个新进程，这个时候如果你用at exit组件打点就会发现整个环境都是重新import+init出来的，然后这个问题就会又出来...我的解决方案是彻底关闭Logging库，当然这是建立在我们项目的日志记录系统是另外实现的+错误日志纯靠Exception+我们的日志系统

**Comment by cquliujian** [comment]
建议直接把jionlp 和 jiojio 这两个包down到本地，然后把 jionlp/util/logger.py   jiojio/util/logger.py 里的def set_logger(level='INFO', log_dir_name='.jionlp_logs')  改为def set_logger(level='INFO', log_dir_name='None')， 然后再把这两个包的__init__文件里的set_logger函数的log_dir_name给删了（或者直接改为None, 不该logger的文件也行）

**Comment by ViCrack** [comment]
> 建议直接把jionlp 和 jiojio 这两个包down到本地，然后把 jionlp/util/logger.py jiojio/util/logger.py 里的def set_logger(level='INFO', log_dir_name='.jionlp_logs') 改为def set_logger(level='INFO', log_dir_name='None')， 然后再把这两个包的__init__文件里的set_logger函数的log_dir_name给删了（或者直接改为None, 不该logger的文件也行）


XXXX\Lib\site-packages\jiojio\util\logger.py

这个方法目前可行，可以避免写入一堆没人看的日志文件
