### ISSUE TITLE
remove_url不完全符合预期

### ISSUE THREAD

**Issue by OnceJune** [dongrixinyu/JioNLP#15]
输入：
这是一个链接http://t.cn/zQaVuHD这是一个链接http://t.cn/zQaVuHD
这是一个链接http://t.cn/zQaVuHD这是一个链接http://t.cn/zQaVuHD这是一个链接

预期：
这是一个链接这是一个链接
这是一个链接这是一个链接这是一个链接

实际输出：
这是一个链接这是一个链接http://t.cn/zqavuhd
这是一个链接这是一个链接这是一个链接

链接出现在句末的时候没有被清理掉。

**Comment by dongrixinyu** [comment]
已修复！

**Comment by dongrixinyu** [comment]
请点一下  star 谢谢！
