### ISSUE TITLE
增加心理学实验问题[功能请求]

### ISSUE THREAD

**Issue by cindynap** [dongrixinyu/JioNLP#150]
<琳达是个31岁的单身女性，直言不讳，非常聪明；她主修哲学；在学生时代，她深切关注歧视和社会公正问题，还参加了反核示威活动。>

请根据<>的描述判断以下两种情况，哪个答案可能性更大：

A. 琳达是银行出纳。
B. 琳达是银行出纳，积极参与女权运动。

这是一个典型的心理学届和概率有关的问题考AI，测试前以为这样的公共知识AI们应该都有比较统一的答案.结果出乎意料，只能感慨AI们真的太能掰了，尤其是claude...

另外，心理学这类的问题在于正常人都答错或者有盲点误区，然后心理学家分析这种现象找到本质。所以我认为ai要真的模拟人，那答案得选择错误的，然后扮演实验对象自圆其说，再扮演心理学家分析错误 ╭(ᵔ_>ᵔ)╮

![Screenshot_20230621_125937](https://github.com/dongrixinyu/JioNLP/assets/12702141/104e1924-4047-463a-9bb2-94dcb7cd7ca6)

![Screenshot_20230621_130028](https://github.com/dongrixinyu/JioNLP/assets/12702141/6ff457e2-09ab-496e-8b26-48a00df8be8a)

![Screenshot_20230621_125802_com poe android_edit_845512623038690](https://github.com/dongrixinyu/JioNLP/assets/12702141/46ab2e75-687b-4532-a901-5c1d0f1f1e44)

![Screenshot_20230621_130224](https://github.com/dongrixinyu/JioNLP/assets/12702141/26e50d40-878c-47ca-ba01-98c512789b6d)

![Screenshot_20230621_130310](https://github.com/dongrixinyu/JioNLP/assets/12702141/375ec245-798d-4bd5-8437-5bc35a497dda)

**Comment by dongrixinyu** [comment]
收到

**Comment by dongrixinyu** [comment]
但我get 不到，模型应该怎么回答这个问题，怎么说都有理啊

**Comment by cindynap** [comment]
这个问题的正确答案，用逻辑用概率用数学的角度来看，要选A啊，B是A的子集...A的可能性概率更大

但是加入人这个大变量以后...

冬日新雨 ***@***.***> 于 2023年6月26日周一 上午4:03写道：
