### ISSUE TITLE
日志打印开关

### ISSUE THREAD

**Issue by wAnFen1017** [dongrixinyu/JioNLP#152]
我将JioNLP用在scrapy项目中用于解析时间，但是当我启动多个爬虫时会报以下错误

PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\xxx\\.jionlp_logs\\log.txt' -> 'C:\\Users\\xxx\\.jionlp_logs\\log.txt.20230705'

虽然并没有影响程序往下执行，但是能不能增加一个记录日志的开关选项用以关闭呢？感谢

**Comment by dongrixinyu** [comment]
[日志打印问题](https://github.com/dongrixinyu/JioNLP/issues/146)
