### ISSUE TITLE
[BUG] 日志打印无法正常关闭

### ISSUE THREAD

**Issue by LBYPatrick** [dongrixinyu/JioNLP#153]
# I. 描述(Description)

多进程的情况下logging根本关不掉(可以看看我下面用了什么代码关闭) 而且会报一些我们完全不需要看的错误，比如这种：

```bash
[2023-07-23 09:38:28,307] [   ERROR] time_parser.py:1261 - Traceback (most recent call last):
  File "/root/autodl-tmp/conda-envs/langchain-test/lib/python3.10/site-packages/jionlp/gadget/time_parser.py", line 981, in parse_time_span_point
    first_full_time_handler, _, _, blur_time = self.parse_time_point(
  File "/root/autodl-tmp/conda-envs/langchain-test/lib/python3.10/site-packages/jionlp/gadget/time_parser.py", line 1526, in parse_time_point
    raise ValueError('## exception string `{}`.'.format(time_string))
ValueError: ## exception string `2`.
```

这个也是jioNLP用logger打出来的东西，因为我把Logger全局关闭后（我们项目内处理Exception时打印日志不使用logger库）这种东西就没了

另外，我也尝试用了作者提供的关闭日志方法，如下（这段代码出现在了每个用到了jionlp的文件开头）

```python
import jionlp as jio
import jiojio

jio.set_logger(None)
jiojio.set_logger(None)
```

根本没有效果，所以上面的那条错误信息还是在执行了上面的代码后出现的
@dongrixinyu

# II. 版本(Version):

- python 版本: 3.10.12 (miniconda3)
- jionlp 版本: '1.4.41'

# III. jionlp的调用代码与输入文本(Code & Text):
```
# import文本见上

jio.parse_time("2") # 但是是不同的进程在调用这玩意
```

# IV. 调用报错日志如下(Log):

> 见描述

# V. 期望行为(Expectation)

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

这个Log如果我关闭了“日志打印”就不应该打印啊，毕竟这本来就是内部的错误，经查是``time_parser.py``内部1521和1526行打印的东西，但注释暗示着是触发内部fallback用的，那用户为啥要看这个？

**Comment by dongrixinyu** [comment]
![image](https://github.com/dongrixinyu/JioNLP/assets/27001062/59f12eb6-6dee-401c-85e5-78c5e1c5c75b)
日志打印有对应的处理方法。你说的那个是程序本身的报错，你调取的并不是时间字符串，自然要报错。

**Comment by LBYPatrick** [comment]
问题是这行命令是用try except 包起来的，Exception理论上应该是我打印才对(我自己用的不是logging库，格式也跟这个不一样的)，为啥jionlp自己在内部打了？
