### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by xiaoming902** [dongrixinyu/JioNLP#158]
**咨询的功能模块**
时间实体抽取 extract_time

**咨询的具体内容和问题**
怎么样才能把月份提取出来
代码：
import time
import jionlp as jio

text = '【美博会】6月11-13上海美博会倾情打造30+特备活动：中国零售业化妆品经营高峰论坛'
res = jio.ner.extract_time(text, time_base=time.time(), with_parsing=False)
print(res)
[{'text': '11-13', 'offset': [7, 12], 'type': 'time_point'}]

怎么样才能把6月11-13都提取出来

**Comment by dongrixinyu** [comment]
这种只能靠大模型了
