### ISSUE TITLE
entity2tag()有些局限

### ISSUE THREAD

**Issue by WenRichard** [dongrixinyu/JioNLP#16]
## entity2tag() 函数还可以提升一下，看了一下源码标注是按照offset顺序来的，如果ner_entities里面多个entities的offset是乱序的  
比如：  
before：  
 [{'text': '胡静静', 'offset': [0, 3], 'type': 'Person'},{'text': '水利局', 'offset': [4, 7], 'type': 'Orgnization'}]]  
after：
ner_entities =[{'text': '水利局', 'offset': [4, 7], 'type': 'Orgnization'},{'text': '胡静静', 'offset': [0, 3], 'type': 'Person'}]
最后的结果将会变成：  
['O', 'O', 'O', 'O', 'B-Orgnization', 'I-Orgnization', 'E-Orgnization', 'O', 'O', 'O']
非常感谢您的工具，受益很多

- 函数名 function name：
entity2tag()

## 请输入报错的文本，以及代码 please input the text and code

```
# 复制粘贴此处 copy and paste here

```

**Comment by dongrixinyu** [comment]
bug 已修复，请点star，谢谢！
