### ISSUE TITLE
[技术咨询] 关于复合时间文本和事件信息提取

### ISSUE THREAD

**Issue by QAbot-zh** [dongrixinyu/JioNLP#164]
**咨询的功能模块**
- jionlp关于复合时间表达的时间提取准确性问题
- jionlp是否有事件实体抽取（不确定是不是这个术语？）的接口

**咨询的具体内容和问题**
最近使用chatgpt搭建应用的时候，做了一个备忘录功能，主要是通过prompt引导让大模型从自然语言文本中提取时间和事件信息，目前使用准确性极高。也如作者在wiki文章里说的，用大模型一是有点牛刀杀鸡的感觉，二是调用时间上会比本地的nlp package要长，所以也在寻找合适的中文nlp库进行替代，然后就找到jionlp这个库了。不得不说是除大模型外、目前使用起来时间信息提取准确性最好最快的python库了，给大佬点个大大的赞。但是也发现一些问题：
- jionlp库对于复合时间文本的时间提取准确性会变差，如下图中，有时候只关注了“国庆节”，有时候只关注了“第二天”，对于这种带有时间复合的文本在处理上，有什么比较好的方法嘛？
![image](https://github.com/dongrixinyu/JioNLP/assets/40236765/b6d59697-2eb4-4312-8652-ec69035c34e4)
- 事件实体/信息的提取，如前面所说的，我需要做备忘录功能，关注的信息就是时间和事件信息，在功能介绍中似乎还没有这方面的接口，文本总结和关键词提取的接口试了下，也不太适合。这块功能的接口会纳入后续的考虑嘛，或者作者有相关功能的库推荐吗？

附上ChatGPT的解析示例：

![ChatGPT-备忘录测试](https://github.com/dongrixinyu/JioNLP/assets/40236765/ab885e80-9817-4efd-ac30-bc59bd317d70)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/dongrixinyu/JioNLP/wiki)

- **请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
复合时间就推荐用大模型来搞。正则来搞成本太大。
