### ISSUE TITLE
[BUG]数字实体('二十一\三十一\二十七点三')被当成时间实体被抽取了

### ISSUE THREAD

**Issue by erhuli** [dongrixinyu/JioNLP#168]
**描述(Description)**
time_strs = jio.ner.extract_time(text, with_parsing=True)
数字实体被当成时间实体被抽取了

原始:"二十一"  抽取结果:"十一"
原始:"三十一"  抽取结果:"十一"
原始:"一百二十一"  抽取结果:"十一"
原始:"二十七点三"  抽取结果:"十七点"

1. 版本(Version):
- python 版本:  3.8.16
- jionlp 版本: 1.5.2

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio

def exect_time():
    print(jio.__version__)
    text_list = ['二十一', '三十一', '一百二十一', '二十七点三']
    for text in text_list:
        time_strs = jio.ner.extract_time(text, with_parsing=True)
        time_text = time_strs[0].get('text')
        print(f'原始:\"{text}\"  抽取结果:\"{time_text}\"')
```

**Comment by dongrixinyu** [comment]
已修复
