### ISSUE TITLE
模型实现语义识别

### ISSUE THREAD

**Issue by lichengyang666** [dongrixinyu/JioNLP#170]
时间语义理解

我想请问一下，以对话形式训练模型理解时间语义，这部分效果会不会比目前的方案要好呢，数据集应该如何构建，参数量比较小的GPT模型可以hold住么

**Comment by dongrixinyu** [comment]
数据集你可以通过jionlp库构建，从大量原始语料中筛。如果模型单独在这个小任务上微调，我觉得应该是可以的。可以试一下，反馈一下模型微调进度
