### ISSUE TITLE
[技术咨询]地址解析慢，耗时3s左右，而官网响应的很快：http://www.jionlp.com/jionlp_online/parse_location

### ISSUE THREAD

**Issue by wangganghua** [dongrixinyu/JioNLP#174]
地址解析模块响应有点慢，官网响应很快

parse_location("格尔木市卫生健康委员会")
耗时 3s左右，
官网链接响应，很快：http://www.jionlp.com/jionlp_online/parse_location

是什么原因导致的？

**Comment by dongrixinyu** [comment]
测第二次调用时间
