### ISSUE TITLE
[BUG] 未来和过去时间段抽取范围不正确

### ISSUE THREAD

**Issue by wkyhit** [dongrixinyu/JioNLP#175]
描述(Description)
import jionlp as jio
jio.parse_time("未来7天", time_base="2023-11-13 00:00:00")
jio.parse_time(“过去7天", time_base="2023-11-13 00:00:00")

结果：
{'type': 'time_span', 'definition': 'blur', 'time': ['2023-11-13 00:00:00', '2023-11-20 23:59:59']}
{'type': 'time_span', 'definition': 'blur', 'time': ['2023-11-06 00:00:00', '2023-11-13 00:00:00']}

问题：
提问中无论是过去7天还是未来7天，得到的时间段范围均为8天。预期得到7天才对。

版本(Version):
* python 版本: 3.10.9
* jionlp 版本: 1.4.40

**Comment by wkyhit** [comment]
此外我还发现，使用jio.ner.extract_time()无法解析带“未来”的时间，但是可以解析带“过去”关键词的时间。
例如：
>>> jio.ner.extract_time("过去7天", time_base="2023-11-13 00:00:00")
[{'text': '过去7天', 'offset': [0, 4], 'type': 'time_span', 'detail': {'type': 'time_span', 'definition': 'blur', 'time': ['2023-11-06 00:00:00', '2023-11-13 00:00:00']}}]

>>> jio.ner.extract_time("未来7天", time_base="2023-11-13 00:00:00")
[{'text': '7天', 'offset': [2, 4], 'type': 'time_delta', 'detail': {'type': 'time_delta', 'definition': 'accurate', 'time': {'day': 7.0}}}]

我阅读代码后发现，parse_time是支持解析“过去”和“未来”时间的，因此ner的时间提取是否需要加上“未来”关键词？
https://github.com/dongrixinyu/JioNLP/blob/master/jionlp/rule/rule_pattern.py的TIME_CHAR_STRING中是否能加上“未来”，以保持parse_time和ner.extract_time的功能一致？

**Comment by dongrixinyu** [comment]
可以的，可以提一个 pr给我
