### ISSUE TITLE
[功能请求]近30日8点，可以解析成近30日或者近30日每天的8点吗

### ISSUE THREAD

**Issue by Reason94** [dongrixinyu/JioNLP#177]
**描述该功能的用处，可以提供相关资料描述该功能**
用户查询报表分析相关功能时，想查看每天某个时间点的数据，会输入“近30日8点的xxx内容”。当前jio无法识别，会报错
<img width="1275" alt="image" src="https://github.com/dongrixinyu/JioNLP/assets/23076822/41fb9685-cca9-4cb7-9895-235a91bb62c2">

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
期望解析成近30日，或者近30日每天的8点

**请顺手 star 一下右上角的⭐小星星**
必须star

**Comment by dongrixinyu** [comment]
我不理解这个近30日是指的哪些天

**Comment by Reason94** [comment]
> 我不理解这个近30日是指的哪些天

从今天算起，前30天。目前jio nlp解析近30日是可以的。解析结果如下
'time': ['2023-10-25 00:00:00', '2023-11-24 14:15:13']

解析近30日8点的话，会报错，如上

**Comment by dongrixinyu** [comment]
这种属于语言歧义了，不论解析成哪一种，总会有错误。最好的解决方案，还是调用gpt
