### ISSUE TITLE
[BUG]  import jionlp 时候会默认创建/.jionlp_logs文件夹，报permission denied

### ISSUE THREAD

**Issue by y111x** [dongrixinyu/JioNLP#183]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)
import jionlp 时候会默认创建/.jionlp_logs文件夹，报permission denied

1. 版本(Version):
- python 版本: python3.6
- jionlp 版本: 1.5.6

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
```

3. 调用报错日志如下(Log):
```
permission denied ：'/.jionkp-logs'
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)
部分公司应用权限管理比较严格，会导致import时候创建日志文件夹失败，建议是否能源码去掉创建文件夹，由用户去判断是否创建日志文件夹。

**Comment by dongrixinyu** [comment]
也可以，我不提供日志服务

**Comment by ViCrack** [comment]
这个运行次数一多jiojio_logs文件夹会写入一堆的无用的txt，而且这个多进程的时候还容易冲突。。。建议作者默认场景下日志不要写入文件

**Comment by xwsat** [comment]
多个环境下引发permission denied,建议去掉
