### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dywlegend1002** [dongrixinyu/JioNLP#187]
```
import jionlp as jio
jio.parse_location('莱芜')
```
{'province': '山东省',
 'city': '莱芜市',
 'county': '钢城',
 'detail': '',
 'full_location': '山东省莱芜市钢城',
 'orig_location': '莱芜'}

百度百科：莱芜区，隶属于山东省济南市

地区更新，没有更新导致，建议修复这几年区改的缺陷～

**Comment by dongrixinyu** [comment]
已修复
