### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by odinchang2022** [dongrixinyu/JioNLP#188]
你好~我想要在程序运行的时候开头不要输出以下这个，但是我看了文档尝试设定log level=None还是一样变成预设的INFO设成其他的像是WARN，LEVEL会变成WARN但是都还是一样会进行输出，请问我该哪里设置

[INFO 2024-02-04 10:49:58,461 set_logger:99] -------------------- logging start -------------------- 
[INFO 2024-02-04 10:49:58,461 set_logger:100] LEVEL: INFO 
[INFO 2024-02-04 10:49:58,461 set_logger:102] PATH:  C:\Users\odinc\.jionlp_logs 
[INFO 2024-02-04 10:49:58,461 set_logger:103] ------------------------------------------------------- 
# jionlp - 微信公众号: JioNLP  Github: `https://github.com/dongrixinyu/JioNLP`.
# jiojio - `http://www.jionlp.com/jionlp_online/cws_pos` is available for online trial.
[INFO 2024-02-04 10:49:58,473 set_logger:92] -------------------- logging start -------------------- 
[INFO 2024-02-04 10:49:58,473 set_logger:93] LEVEL: INFO 
[INFO 2024-02-04 10:49:58,473 set_logger:95] PATH:  C:\Users\odinc\.jiojio/jiojio_logs 
[INFO 2024-02-04 10:49:58,473 set_logger:96] -------------------------------------------------------

**Comment by dongrixinyu** [comment]
你可以试试把 __init__.py 文件里的 set_logger 函数去掉，换成默认的 import logging

**Comment by odinchang2022** [comment]
请教一下可以在Python程序内设定吗？因为我这环境有部署到很多台电脑，都跑到个电脑下面去改包内的 __init__.py 有点累

**Comment by CuteCha** [comment]
your_path/site-packages/jionlp/util/help_search.py   ---line 32
your_path/site-packages/jiojio/__init__.py ---line 20
