### ISSUE TITLE
[BUG]    在docker容器中运行，超过一定的时间，比如隔天后，解析时间不正确。

### ISSUE THREAD

**Issue by jovian1994** [dongrixinyu/JioNLP#189]
**描述(Description)**
在docker容器中运行，超过一定的时间，比如隔天后，解析时间不正确。
> 描述你遇到了什么问题
我把您的项目集成到了我的flask项目中，该项目跑在dokcer容器中，使用的服务器是uwsgi。并在dockerfile中设置了时区为Asia/shanghai

1. 版本(Version):
- python 版本:  3.10
- jionlp 版本: 1.5.6

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
res = jio.parse_time('昨天下午两点')
```

**期望行为(Expectation)**
比如今天是2月20日，当我我容器启动后我发送请求调用解析函数，此时拿到的结果是正确的。也就是返回的是2024-02-19:14:00 
但是 隔了一天我我再次调用接口  也就是21日调用接口。此时会依然返回2024-02-19:14:00  按照道理上来说应该是拿到2024-02-20:14:00 

此时 我在容器中手动执行解析的函数 拿到的结果是对的，但是调用接口的就不对。我不明白是为啥。

**Comment by slliao445** [comment]
我也遇到了这个问题，请问怎么解决的呢？
