### ISSUE TITLE
抽取金额字符串功能中对于口语化似乎不太支持

### ISSUE THREAD

**Issue by WangJerry1229** [dongrixinyu/JioNLP#19]
## 请输入您的问题描述，或您预期的功能 please describe the bug or the function you expect

例如：十块五 八块五毛钱 这类口语化的金额表示似乎无法支持 
不过想了一下这些说法要想识别确实容易和其他量词产生冲突 不知道有没有合适的解决方法

**Comment by dongrixinyu** [comment]
这些表达，也可以添加到正则里。只要不产生歧义都可以。

**Comment by dongrixinyu** [comment]
十块五 ：有歧义，“烧饼十块五个”不做处理。
八块五毛 ：已修复，
八块五毛钱 ：已修复，

**Comment by WangJerry1229** [comment]
十分感谢 辛苦了
