### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gj-zhang** [dongrixinyu/JioNLP#190]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)
<img width="1162" alt="image" src="https://github.com/dongrixinyu/JioNLP/assets/21170229/2edbd482-de19-472c-a111-6bb1016c0798">

1. 版本(Version):
- 官网在线试用

2. jionlp的调用代码与输入文本(Code & Text):
```
无
```

3. 调用报错日志如下(Log):
```
无
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)
希望 2024年1月30到2024年2月28 这段文本 可以返回 和 2024年1月30号到2024年2月28号一样的结果

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
1月30  这种表达有歧义，明确 1月30号，或1月30日，就没问题了。
