### ISSUE TITLE
[BUG]提取2024年冬至的时候，会提取到 2024年冬，实际提取到了 立冬的日期

### ISSUE THREAD

**Issue by locasxe** [dongrixinyu/JioNLP#198]
**描述(Description)**
如题， 运行函数 jio.ner.extract_time("2024年冬至")
得到 2024-11-07 日期， 实际应该是 2024-12-21
应该是提取到了立冬的日期？

- python 版本: 3.9
- jionlp 版本: 最新

**Comment by dongrixinyu** [comment]
已修复
