### ISSUE TITLE
[技术咨询] 关于多线程地址解析性能问题

### ISSUE THREAD

**Issue by yclnycl** [dongrixinyu/JioNLP#204]
**咨询的功能模块**
- 请描述您想咨询jionlp的哪部分功能
多线程地址解析性能问题

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 目前我本地开十个线程地址解析, qps只有200左右,但是我不用多线程直接跑qps有300左右,请问下性能调优和什么相关

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/dongrixinyu/JioNLP/wiki)

- **请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
python 哪来的多线程，只有多进程吧
