### ISSUE TITLE
数据增强里面的文本替换增删为啥不是词级别的

### ISSUE THREAD

**Issue by xxllp** [dongrixinyu/JioNLP#21]
现在的random_add_delete等文本增强函数都是char 级别的 输出的结果看着比较诡异

原始文本包含的时间 人名等都会被变了

**Comment by dongrixinyu** [comment]
代码里的注释有详细的说明，
1、词级别的替换，想要看着连贯得用到语言模型，单纯同义词近义词替换，出来的结果也一样很诡异。这个工具包不打算加入模型。
2、只要nlp任务不依赖文本的时间和人名，替换掉都是无所谓的。
