### ISSUE TITLE
[BUG]解析20240307这种时间格式与预期不符

### ISSUE THREAD

**Issue by windsunboyu** [dongrixinyu/JioNLP#211]
**描述(Description)**

> 解析20240307这种时间格式与预期不符，期望输出当天的时间，结果输出了全年

1. 版本(Version):
- python 版本: 3.9.10
- jionlp 版本: 1.5.11

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
res = jio.parse_time('查询20240307计划')
print(res)
```

3. 调用报错日志如下(Log):
```
{'type': 'time_span', 'definition': 'accurate', 'time': ['2024-01-01 00:00:00', '2024-12-31 23:59:59']}
```

**期望行为(Expectation)**

{'type': 'time_point', 'definition': 'accurate', 'time': ['2024-03-07 00:00:00', '2024-03-07 23:59:59']}

**Comment by dongrixinyu** [comment]
fixed
