### ISSUE TITLE
部分地址未能解析（2024.5.23）

### ISSUE THREAD

**Issue by saogedangransao** [dongrixinyu/JioNLP#212]
**
目前在做地理解析的是后有部分城市识别不出来
例子：
1、吉林省吉林----期望结果---》吉林省吉林市
2、新疆巴音郭楞---期望结果---》新疆维吾尔族自治区巴音郭楞蒙古自治州
**

> 上述两个例子中，例子1中无法识别第二个吉林，例子2中的【巴音郭楞】未能解析出【巴音郭楞蒙古自治州】
**

1. 版本(Version):
- python 版本:3.12.2
- jionlp 版本: '1.5.11'

2. jionlp的调用代码与输入文本(Code & Text):
```
df["市"] = df["地址"].apply(
    lambda x: jio.parse_location(x, town_village=True, change2new=True)["city"]
)
df["省"] = df["地址"].apply(
    lambda x: jio.parse_location(x, town_village=True, change2new=True)["province"]
)
```

**Comment by dongrixinyu** [comment]
吉林省吉林有问题。必须得加市，否则是歧义。巴音郭楞修复了

**Comment by saogedangransao** [comment]
你好，我已经收到您的来件。
