### ISSUE TITLE
怎么更新地址表？

### ISSUE THREAD

**Issue by tendrillion** [dongrixinyu/JioNLP#215]
怎么更新地址表？
能否新增识别和提取台湾和香港的地址？

**Comment by dongrixinyu** [comment]
地名文件在库里， dictionary里。你可以参考添加那部分内容

**Comment by tendrillion** [comment]
> 地名文件在库里， dictionary里。你可以参考添加那部分内容

能否新增识别和提取台湾和香港的地址？

**Comment by dongrixinyu** [comment]
你可以参考库里的 数据文件添加
