### ISSUE TITLE
[技术咨询]分词和词性标注在线体验地址是哪个？

### ISSUE THREAD

**Issue by muhm21cn** [dongrixinyu/JioNLP#218]
**咨询的具体内容和问题**
- 哪里可以在线体验分词和词性标注，http://www.jionlp.com/jionlp_online/cws_pos  这个地址没有可以输入文字的地方。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/dongrixinyu/JioNLP/wiki)

- **请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
直接下载使用吧，网站不赚钱快要关了
