### ISSUE TITLE
十一上午十一点十一 无法识别[BUG]

### ISSUE THREAD

**Issue by www516717402** [dongrixinyu/JioNLP#219]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: (通过 `python` 可查)
- jionlp 版本: (通过 `jionlp.__version__` 可查)

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
res = jio.parse_time('XXXX')
print(res)
```

3. 调用报错日志如下(Log):
```
xxxxxxxxxxxx
e.g.
trackback: XXXXXX
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

**Comment by Sh1k17** [comment]
http://www.jionlp.com/jionlp_online/parse_time 我发现这个在线的工具可以成功解析出来对应的时间，但是jionlp不可以，可以请作者解释一下这是为什么吗？同样的 ”明天下午1点15“ 也不可以 @dongrixinyu

**Comment by www516717402** [comment]
> http://www.jionlp.com/jionlp_online/parse_time 我发现这个在线的工具可以成功解析出来对应的时间，但是jionlp不可以，可以请作者解释一下这是为什么吗？同样的 ”明天下午1点15“ 也不可以 @dongrixinyu

因为修改一个问题，造成另外一个问题的bug。我试了之前的版本也是可以的

**Comment by www516717402** [comment]
基于正则的方法，就更容易出现这种情况。在项目中自己维护一下

> > http://www.jionlp.com/jionlp_online/parse_time 我发现这个在线的工具可以成功解析出来对应的时间，但是jionlp不可以，可以请作者解释一下这是为什么吗？同样的 ”明天下午1点15“ 也不可以 @dongrixinyu
> 
> 因为修改一个问题，造成另外一个问题的bug。我试了之前的版本也是可以的
