### ISSUE TITLE
地址解析错误

### ISSUE THREAD

**Issue by tendrillion** [dongrixinyu/JioNLP#221]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.10
- jionlp 版本: 1.5.14

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
res =jio.parse_location("青海西宁",town_village=False)
print(res)
```
地址解析时，青海西宁-被识别成-海西蒙古族藏族自治州

**Comment by dongrixinyu** [comment]
已修复
