### ISSUE TITLE
[BUG] 路名中有“香港”会导致省市匹配错误

### ISSUE THREAD

**Issue by LymphV** [dongrixinyu/JioNLP#222]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**
> 对路名中含有“香港”的地名会优先匹配省份，导致省市匹配错误
> 在提供的在线工具中效果与自己脚本执行一致，均为错误的 “香港特别行政区”
> ![image](https://github.com/user-attachments/assets/67841949-809f-4d31-9bbd-0db8b26ff499)
> 使用的地址均为能够在天眼查中查到的企业工商注册地址

1. 版本(Version):
- python 版本: 3.9.13
- jionlp 版本: 1.5.15

2. jionlp的调用代码与输入文本(Code & Text):
```
from jionlp import parse_location
ss = [
    '青岛市市南区香港中路18号',
    '深圳市南山区高新区南区粤兴一道8号香港城市大学',
    '青岛市市北区广东路48号',
]
for s in ss:
    r=parse_location(s)
    print (s)
    print ('\t', r['province'], r['city'], r['county'], r['detail'])
```

3. 调用报错日志如下(Log):

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

- 青岛市市南区香港中路18号
  - 香港特别行政区 香港 南区  香港中路18号
  - 错误，期望：山东省 青岛市 市南区
- 深圳市南山区高新区南区粤兴一道8号香港城市大学
  - 香港特别行政区 香港 南区 粤兴一道8号香港城市大学
  - 错误，期望：广东省 深圳市 南山区
- 青岛市市北区广东路48号
  - 山东省 青岛市 市北区 广东路48号
  - 正确，“广东”不会被优先匹配
- 石首市笔架山办事处建设路香港城西街
  - 香港特别行政区 香港 None 城西街
  - 错误，期望：湖北省 荆州市 石首市 笔架山办事处建设路香港城西街
- 武汉市江岸区澳门路
  - 湖北省 武汉市 江岸区 澳门路
  - 正确，“澳门”不会被优先匹配

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
已修复
