### ISSUE TITLE
ValueError: the given string `早` is illegal

### ISSUE THREAD

**Issue by ZL-0105** [dongrixinyu/JioNLP#23]
## 请输入您的问题描述，或您预期的功能 please describe the bug or the function you expect

- 函数名 function name：
parse_time

## （*** 一定要写清楚是具体哪一条文本数据造成了报错！！！ ***）

```

# 复制粘贴此处 copy and paste here

```市政协十三届四次会议举行第二次全体会议|漳州新闻网讯(记者 张志鹏)1月3日下午，市政协十三届四次会议举行第二次全体会议，听取委员大会发言。10位政协委员分别代表有关专委会、民主党派、人民团体作大会发言。市政协十三届四次会议执行主席张祯锦、柳建聪、黄井南、杨胜华、吴芳华、陈跃鸿、何伟燕、卢力、李扬真及值日常委在主席台就座。市领导邵玉龙、刘远、阮开森、张慧德、李珊珊、谢毅泰、张翼腾、兰万安、陈水树、吴卫红应邀出席会议并在主席台就座，在漳省政协委员、市直及驻漳有关单位领导、漳州异地商会和异地漳州商会会长等应邀列席会议，听取委员发言。10位委员就全市经济社会发展及民生改善等领域提出意见和建议。刘志明代表漳州市政协经济委员会发言，提出关于加快漳州智能制造发展的建议；王金泉代表九三学社漳州市委员会发言，提出关于进一步激活我市“夜间经济”的建议；蔡晓洁代表民盟漳州市委员会发言，提出打造龙头深化融合、推动职教高质量发展的建议；张建国代表农工党漳州市委员会发言，提出关于进一步推进我市县域紧密型医共体建设的建议；颜小燕代表民进漳州市委员会发言，提出持续优化营商环境、加快漳州台资工业发展的建议；苏美华代表漳州市政协教科卫体委员会发言，提出关于把中国女排漳州体训基地建设成城市新形象标志性区域的建议；刘丽贞代表漳州市政协提案委员会发言，提出关于试行“时间银行”互助养老模式的建议；杨栋代表漳州市政协特邀(二)界发言，提出关于加强漳州古城运营与管理的几点建议；陆銮眉代表漳州市政协农业和农村委员会发言，提出关于扶持我市休闲食品制造产业的建议；陈婉儿代表共青团漳州市委员会发言，提出关于进一步推进漳台青年交流融合的建议。会上还有15个单位分别围绕优化钢铁产业布局推动高质量发展；发起“太平洋海上丝绸之路”联合申遗倡议；破解医养结合瓶颈；把握新机遇、提振民营企业发展信心；加快推进漳州儒学遗址保护与合理利用；推进0-3岁儿童早期发展项目工作；加强食品“三小”监管工作；推动我市小流域治理；推进厦门湾南岸交通环境建设；推动漳州工业高质量发展的路径与对策；落实好支持漳州民营企业发展政策增强实体经济竞争力；加强漳州市青少年科技教育；落实“两岸一家亲”理念、提升两岸婚姻家庭的服务水平；加强涉侨文物的保护与活化利用助力“一带一路”建设；推进文明城市“妈妈小屋”建设、保障妇女合法权益等方面作书面发言。 http://www.zznews.cn/news/system/2020/01/04/030187660.shtml|新闻|||20200104

## 请输入报错信息与日志追踪 please input the bug info and traceback


Traceback (most recent call last):
  File "D:/论文代码/yidong/test.py", line 32, in <module>
    time = jio.parse_time(line)
  File "D:\compiler\anaconda\lib\site-packages\jionlp\gadget\time_parser.py", line 605, in __call__
    _, second_full_time_handler, _, blur_time = self.parse_time_point(
  File "D:\compiler\anaconda\lib\site-packages\jionlp\gadget\time_parser.py", line 985, in parse_time_point
    cur_hms_func(cur_hms_string)
  File "D:\compiler\anaconda\lib\site-packages\jionlp\gadget\time_parser.py", line 3146, in normalize_blur_hour
    raise ValueError('the given string `{}` is illegal'.format(time_string))
ValueError: the given string `早` is illegal

**Comment by ZL-0105** [comment]
文本数据


市政协十三届四次会议举行第二次全体会议|漳州新闻网讯(记者 张志鹏)1月3日下午，市政协十三届四次会议举行第二次全体会议，听取委员大会发言。10位政协委员分别代表有关专委会、民主党派、人民团体作大会发言。市政协十三届四次会议执行主席张祯锦、柳建聪、黄井南、杨胜华、吴芳华、陈跃鸿、何伟燕、卢力、李扬真及值日常委在主席台就座。市领导邵玉龙、刘远、阮开森、张慧德、李珊珊、谢毅泰、张翼腾、兰万安、陈水树、吴卫红应邀出席会议并在主席台就座，在漳省政协委员、市直及驻漳有关单位领导、漳州异地商会和异地漳州商会会长等应邀列席会议，听取委员发言。10位委员就全市经济社会发展及民生改善等领域提出意见和建议。刘志明代表漳州市政协经济委员会发言，提出关于加快漳州智能制造发展的建议；王金泉代表九三学社漳州市委员会发言，提出关于进一步激活我市“夜间经济”的建议；蔡晓洁代表民盟漳州市委员会发言，提出打造龙头深化融合、推动职教高质量发展的建议；张建国代表农工党漳州市委员会发言，提出关于进一步推进我市县域紧密型医共体建设的建议；颜小燕代表民进漳州市委员会发言，提出持续优化营商环境、加快漳州台资工业发展的建议；苏美华代表漳州市政协教科卫体委员会发言，提出关于把中国女排漳州体训基地建设成城市新形象标志性区域的建议；刘丽贞代表漳州市政协提案委员会发言，提出关于试行“时间银行”互助养老模式的建议；杨栋代表漳州市政协特邀(二)界发言，提出关于加强漳州古城运营与管理的几点建议；陆銮眉代表漳州市政协农业和农村委员会发言，提出关于扶持我市休闲食品制造产业的建议；陈婉儿代表共青团漳州市委员会发言，提出关于进一步推进漳台青年交流融合的建议。会上还有15个单位分别围绕优化钢铁产业布局推动高质量发展；发起“太平洋海上丝绸之路”联合申遗倡议；破解医养结合瓶颈；把握新机遇、提振民营企业发展信心；加快推进漳州儒学遗址保护与合理利用；推进0-3岁儿童早期发展项目工作；加强食品“三小”监管工作；推动我市小流域治理；推进厦门湾南岸交通环境建设；推动漳州工业高质量发展的路径与对策；落实好支持漳州民营企业发展政策增强实体经济竞争力；加强漳州市青少年科技教育；落实“两岸一家亲”理念、提升两岸婚姻家庭的服务水平；加强涉侨文物的保护与活化利用助力“一带一路”建设；推进文明城市“妈妈小屋”建设、保障妇女合法权益等方面作书面发言。 http://www.zznews.cn/news/system/2020/01/04/030187660.shtml|新闻|||20200104

**Comment by dongrixinyu** [comment]
请写清楚输入到 parse_time 的文本！怎么使用的

**Comment by ZL-0105** [comment]
line = "市政协十三届四次会议举行第二次全体会议|漳州新闻网讯(记者 张志鹏)1月3日下午，市政协十三届四次会议举行第二次全体会议，听取委员大会发言。10位政协委员分别代表有关专委会、民主党派、人民团体作大会发言。市政协十三届四次会议执行主席张祯锦、柳建聪、黄井南、杨胜华、吴芳华、陈跃鸿、何伟燕、卢力、李扬真及值日常委在主席台就座。市领导邵玉龙、刘远、阮开森、张慧德、李珊珊、谢毅泰、张翼腾、兰万安、陈水树、吴卫红应邀出席会议并在主席台就座，在漳省政协委员、市直及驻漳有关单位领导、漳州异地商会和异地漳州商会会长等应邀列席会议，听取委员发言。10位委员就全市经济社会发展及民生改善等领域提出意见和建议。刘志明代表漳州市政协经济委员会发言，提出关于加快漳州智能制造发展的建议；王金泉代表九三学社漳州市委员会发言，提出关于进一步激活我市“夜间经济”的建议；蔡晓洁代表民盟漳州市委员会发言，提出打造龙头深化融合、推动职教高质量发展的建议；张建国代表农工党漳州市委员会发言，提出关于进一步推进我市县域紧密型医共体建设的建议；颜小燕代表民进漳州市委员会发言，提出持续优化营商环境、加快漳州台资工业发展的建议；苏美华代表漳州市政协教科卫体委员会发言，提出关于把中国女排漳州体训基地建设成城市新形象标志性区域的建议；刘丽贞代表漳州市政协提案委员会发言，提出关于试行“时间银行”互助养老模式的建议；杨栋代表漳州市政协特邀(二)界发言，提出关于加强漳州古城运营与管理的几点建议；陆銮眉代表漳州市政协农业和农村委员会发言，提出关于扶持我市休闲食品制造产业的建议；陈婉儿代表共青团漳州市委员会发言，提出关于进一步推进漳台青年交流融合的建议。会上还有15个单位分别围绕优化钢铁产业布局推动高质量发展；发起“太平洋海上丝绸之路”联合申遗倡议；破解医养结合瓶颈；把握新机遇、提振民营企业发展信心；加快推进漳州儒学遗址保护与合理利用；推进0-3岁儿童早期发展项目工作；加强食品“三小”监管工作；推动我市小流域治理；推进厦门湾南岸交通环境建设；推动漳州工业高质量发展的路径与对策；落实好支持漳州民营企业发展政策增强实体经济竞争力；加强漳州市青少年科技教育；落实“两岸一家亲”理念、提升两岸婚姻家庭的服务水平；加强涉侨文物的保护与活化利用助力“一带一路”建设；推进文明城市“妈妈小屋”建设、保障妇女合法权益等方面作书面发言。 http://www.zznews.cn/news/system/2020/01/04/030187660.shtml|新闻|||20200104"


time = jio.parse_time(line, time_base={'year': 2020})

**Comment by ZL-0105** [comment]
推进0-3岁儿童早期发展项目工作

应该是上面这句话出错了

**Comment by dongrixinyu** [comment]
这个工具不是这么用的，要先做 实体识别，把时间字符串抽取出来，然后再用解析工具解析语义。
