### ISSUE TITLE
[BUG]将其它的数字串识别为时间

### ISSUE THREAD

**Issue by sajiofni** [dongrixinyu/JioNLP#238]
**描述(Description)**
错误解析了 id 串

1. 版本(Version):
- python 版本:  3.10.9
- jionlp 版本: 1.5.15

2. jionlp的调用代码与输入文本(Code & Text):

```
 jio.parse_time('请帮忙解读告警信息,告警ID为:172662768690099', time_base=time.time())
{'type': 'time_span', 'definition': 'accurate', 'time': ['1726-01-01 00:00:00', '1726-12-31 23:59:59']}
```

**期望行为(Expectation)**
id的类似串，不进行识别，或做其他配置不进行解析

**Comment by dongrixinyu** [comment]
这种应该调用 jio.ner.extract_time
