### ISSUE TITLE
location_parser中的报错问题

### ISSUE THREAD

**Issue by liyongkang123** [dongrixinyu/JioNLP#29]
**提 issue 请务必将以下信息写清楚，否则无法解答！！！**
**描述(Description)**
使用地址解析功能，如果text为“上门西湖区蒋村花园小区管局农贸市场高高兴兴”,会报错TypeError: sequence item 0: expected str instance, NoneType found

需要把location_parser.py中的第279行修改为 key_name = ''.join( [str(prov), str(city), str(county)])
已解决

**Comment by dongrixinyu** [comment]
已修改。后续会对地址解析再进一步优化细节解析。
