### ISSUE TITLE
回译的API没用了

### ISSUE THREAD

**Issue by WindSearcher** [dongrixinyu/JioNLP#31]
import jionlp as jio
google_api = jio.GoogleApi()
baidu_api = jio.BaiduApi(
    [{'appid': '*',
      'secretKey': '*'}], gap_time=0.5
)
apis = [baidu_api,google_api]
back_trans = jio.BackTranslation(mt_apis=apis)
text = '饿了么凌晨发文将推出新功能，用户可选择是否愿意多等外卖员 5 分钟，你愿意多等这 5 分钟吗？'
print(baidu_api(text))  # 使用接口做单次调用
result = back_trans(text)
print(result)
报一下的错，这里我隐藏了appid和secret
``jio.help()` is provided to search how to use jio functions.
Traceback (most recent call last):
  File "E:/python/code/nlp/学术论文分类/LGB推特情感分析.py", line 123, in <module>
    print(baidu_api(text))  # 使用接口做单次调用
  File "E:\install\pythonEnv\lib\site-packages\jionlp\textaug\back_translation\translation_api.py", line 43, in wrapper
    from_lang = kargs['from_lang']
KeyError: 'from_lang'`

**Comment by dongrixinyu** [comment]
首先，不论 baidu_api 还是 google_api，它都是可以单独去回译文本的，BackTranslation 只是对这些所有的 api 做了一个统一的管理和控制。appid 等参数，这不是我规定的，这是百度规定的。所以是必须填写的。百度开放了100万免费额度。你可以自己去申领，填上去，用这个框架就可以回译了。不填参数必然报错失败。

**Comment by WindSearcher** [comment]
主要是用你的实例代码出现的问题呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongrixinyu/JioNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dongrixinyu/JioNLP] 回译的API没用了 (#31)





 
首先，不论 baidu_api 还是 google_api，它都是可以单独去回译文本的，BackTranslation 只是对这些所有的 api 做了一个统一的管理和控制。appid 等参数，这不是我规定的，这是百度规定的。所以是必须填写的。百度开放了100万免费额度。你可以自己去申领，填上去，用这个框架就可以回译了。不填参数必然报错失败。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongrixinyu** [comment]
确实是一个bug，下一个commit就修复了

**Comment by WindSearcher** [comment]
> 
> 
> 确实是一个bug，下一个commit就修复了

期待大佬的commit

**Comment by dongrixinyu** [comment]
修复了

**Comment by WindSearcher** [comment]
> 
> 
> 修复了

谷歌翻译的免费API还能用嘛，刚试了下，没用

**Comment by WindSearcher** [comment]
> 
> 
> 修复了

这个1.3.36版本还没发布吧

**Comment by dongrixinyu** [comment]
> > 修复了
> 
> 这个1.3.36版本还没发布吧

谷歌的是卡，它有反爬，响应会变慢。

pip发版会比较慢。优先从 git 上拉是比较新的
