### ISSUE TITLE
[BUG]URL正则匹配错误

### ISSUE THREAD

**Issue by JianWenJun** [dongrixinyu/JioNLP#38]
**描述(Description)**
URL正则匹配错误
> 描述你遇到了什么问题(Please description your issue here)
调用remove_url函数时出现不能匹配的情况
1. 版本(Version):

2. jionlp的调用代码与输入文本(Code & Text):
```
sent1 = "抖音知识分享 https://v.douyin.com/RtKFFah/ 复制Ci鏈接，打开Dou音搜索，直接观看視頻"
sent2 = "抖音知识分享https://v.douyin.com/RtKFFah/复制Ci鏈接，打开Dou音搜索，直接观看視頻"
print("1", jionlp.remove_url(sent1))
print("2", jionlp.remove_url(sent2))
```

3. 调用报错日志如下(Log):
```
1.抖音知识分享 https://v.douyin.com/RtKFFah/ 复制Ci鏈接，打开Dou音搜索，直接观看視頻
2.抖音知识分享复制Ci鏈接，打开Dou音搜索，直接观看視頻
```

**期望行为(Expectation)**

☝️输出【抖音知识分享复制Ci鏈接，打开Dou音搜索，直接观看視頻】才是正确的

**请顺手 star 一下右上角的⭐小星星**

**Comment by JianWenJun** [comment]
删掉remove_url 函数中的【text = ''.join(['￥', text, '￥'])】代码即可正常，想问一下加【text = ''.join(['￥', text, '￥'])】这段代码的考虑因素是？

**Comment by JianWenJun** [comment]
还有想问一下，remove_url这个函数中的 【text = ''.join(['￥', text, '￥'])】这段代码的目的是？谢谢～！

**Comment by dongrixinyu** [comment]
已修复。
【text = ''.join(['￥', text, '￥'])】 这个是为了少写一条正则所以强行搞了个文本的边界。
感谢。
