### ISSUE TITLE
python>3.9有没有办法安装呢

### ISSUE THREAD

**Issue by Dragon-Wu** [dongrixinyu/JioNLP#40]
安装时还是会报pkuseg错误，有没有办法绕过嘞，其实自己使用的功能也没用到分词相关的，而且环境已经装了很多包，不方便再重新搭了T T

**Comment by dongrixinyu** [comment]
https://pypi.org/project/jionlp-py39/

参考一下这个。这是其它人调过的py39版本
主要原因是因为 pkuseg 影响了安装。后续会开发效果速度更好的 jiojio 分词器。

**Comment by Dragon-Wu** [comment]
> https://pypi.org/project/jionlp-py39/
> 
> 参考一下这个。这是其它人调过的py39版本 主要原因是因为 pkuseg 影响了安装。后续会开发效果速度更好的 jiojio 分词器。

可以的，另外pkuseg也已经可以修复这个问题，https://github.com/explosion/spaCy/discussions/7370，可以用上面的方法先装pkuseg，然后再装jionlp；
另外，补充一个括号，因为最近自己在做一些清理，jionlp的删除和提取括号挺方便的，但不够全，因为有的文本很杂乱，会有全半角和一些奇怪的括号，可以补充一下brackets = r"｛｝{}「」[]【】()〔〕（）<>〈〉＜＞《》〖〗"
最后，感谢您的工作，很不错，希望以后也有时间也写一些有用的工具能帮上您

**Comment by dongrixinyu** [comment]
> 

   谢谢，可以添加

**Comment by FYWinds** [comment]
#41
我把jionlp-py39的修改放在了这个pr中
如果作者认为不会对开发造成太大影响的话可以考虑merge一下

（由于偷懒所以jionlp-py39目前还没有自动部署，因此会落后n个版本）
