### ISSUE TITLE
时间语义分析对于“和”的判断[BUG]

### ISSUE THREAD

**Issue by dong706** [dongrixinyu/JioNLP#45]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本:3.8
- jionlp 版本: 1.3.47

2. jionlp的调用代码与输入文本(Code & Text):
```
对于“每周一9点和14点”的，返回如下：
[
	{
		"detail": {
			"definition": "accurate",
			"time": {
				"delta": {
					"day": 7
				},
				"point": {
					"string": "周一9点",
					"time": [
						"2022-02-28 09:00:00",
						"2022-02-28 09:59:59"
					]
				}
			},
			"type": "time_period"
		},
		"offset": [
			0,
			5
		],
		"text": "每周一9点",
		"type": "time_period"
	},
	{
		"detail": {
			"definition": "accurate",
			"time": [
				"2022-03-05 14:00:00",
				"2022-03-05 14:59:59"
			],
			"type": "time_point"
		},
		"offset": [
			6,
			9
		],
		"text": "14点",
		"type": "time_point"
	}
]
```

3. 调用报错日志如下(Log):
```
对于这个“和14点”的解析貌似不正确，求修复或者有什么方案能解决？感谢！
```

**期望行为(Expectation)**

> 返回正确的解析结果

**Comment by dong706** [comment]
不过，对于“每周一9点和每周一14点提醒我”是解析结果是正确的，所以这个...可能不算一个BUG了。

**Comment by dongrixinyu** [comment]
> 每周一9点和14点

是bug，我一开始没考虑到这种类型，所以返回的数据结构还需要再改一下。我最早关于 `和` 的想法是，`时间1` 和 `时间2`，首先解析`时间1`，然后以 `时间1` 为 time_base ,解析 `时间 2`。


看看这样可不可以，如果没问题，就按这样的方式来处理。

**Comment by dong706** [comment]
> > 每周一9点和14点
> 
> 是bug，我一开始没考虑到这种类型，所以返回的数据结构还需要再改一下。我最早关于 `和` 的想法是，`时间1` 和 `时间2`，首先解析`时间1`，然后以 `时间1` 为 time_base ,解析 `时间 2`。
> 
> 看看这样可不可以，如果没问题，就按这样的方式来处理。

没有问题，感谢！
