### ISSUE TITLE
python 3.9.10安装失败

### ISSUE THREAD

**Issue by chenjie1234567890** [dongrixinyu/JioNLP#46]
python版本：3.9.10
pip版本：22.0.4
操作系统：windows10
下载源：清华（https://pypi.tuna.tsinghua.edu.cn/simple）

错误日志：
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting jionlp
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/54/81/72112e67f4de08db3b701e36f69318c79540f67916fc6ab26c91995725fd/jionlp-1.3.47-py2.py3-none-any.whl (19.0 MB)
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/64/3a/090a533c7f0682d653633cfd2d33e9aab3e671379fb199aeb7fa9bd3c34a/pkuseg-0.0.25.tar.gz (48.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: jieba in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from jionlp) (0.42.1)
Requirement already satisfied: numpy in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from jionlp) (1.22.2)
Requirement already satisfied: requests in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from jionlp) (2.27.1)
Requirement already satisfied: zipfile36 in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from jionlp) (0.1.3)
Requirement already satisfied: cython in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from pkuseg->jionlp) (0.29.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from requests->jionlp) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from requests->jionlp) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from requests->jionlp) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages (from requests->jionlp) (2.0.12)
Using legacy 'setup.py install' for pkuseg, since package 'wheel' is not installed.
Installing collected packages: pkuseg, jionlp
  Running setup.py install for pkuseg: started
  Running setup.py install for pkuseg: finished with status 'error'
  error: subprocess-exited-with-error

  Running setup.py install for pkuseg did not run successfully.
  exit code: 1

  [63 lines of output]
  running install
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\config.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\data.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\download.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\gradient.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\model.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\optimizer.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\res_summarize.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\scorer.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\trainer.py -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\__init__.py -> build\lib.win-amd64-3.9\pkuseg
  creating build\lib.win-amd64-3.9\pkuseg\dicts
  copying pkuseg\dicts\__init__.py -> build\lib.win-amd64-3.9\pkuseg\dicts
  creating build\lib.win-amd64-3.9\pkuseg\models
  copying pkuseg\models\__init__.py -> build\lib.win-amd64-3.9\pkuseg\models
  creating build\lib.win-amd64-3.9\pkuseg\postag
  copying pkuseg\postag\model.py -> build\lib.win-amd64-3.9\pkuseg\postag
  copying pkuseg\postag\__init__.py -> build\lib.win-amd64-3.9\pkuseg\postag
  creating build\lib.win-amd64-3.9\pkuseg\models\default
  copying pkuseg\models\default\__init__.py -> build\lib.win-amd64-3.9\pkuseg\models\default
  copying pkuseg\feature_extractor.pyx -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\inference.pyx -> build\lib.win-amd64-3.9\pkuseg
  copying pkuseg\dicts\default.pkl -> build\lib.win-amd64-3.9\pkuseg\dicts
  copying pkuseg\postag\feature_extractor.pyx -> build\lib.win-amd64-3.9\pkuseg\postag
  copying pkuseg\models\default\features.pkl -> build\lib.win-amd64-3.9\pkuseg\models\default
  copying pkuseg\models\default\weights.npz -> build\lib.win-amd64-3.9\pkuseg\models\default
  running build_ext
  skipping 'pkuseg\inference.cpp' Cython extension (up-to-date)
  cythoning pkuseg/feature_extractor.pyx to pkuseg\feature_extractor.c
  cythoning pkuseg/postag/feature_extractor.pyx to pkuseg/postag\feature_extractor.c
  building 'pkuseg.inference' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\pkuseg
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\JieBrother\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\include -IC:\Users\JieBrother\AppData\Local\Programs\Python\Python39\include -IC:\Users\JieBrother\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt /EHsc /Tppkuseg\inference.cpp /Fobuild\temp.win-amd64-3.9\Release\pkuseg\inference.obj
  inference.cpp
  c:\users\jiebrother\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  pkuseg\inference.cpp(3118): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  pkuseg\inference.cpp(4284): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
  pkuseg\inference.cpp(4285): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
  pkuseg\inference.cpp(5108): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  pkuseg\inference.cpp(6219): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  pkuseg\inference.cpp(6807): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data
  pkuseg\inference.cpp(23619): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
  pkuseg\inference.cpp(23624): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
  pkuseg\inference.cpp(23639): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
  pkuseg\inference.cpp(23652): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
  pkuseg\inference.cpp(24323): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
  pkuseg\inference.cpp(24339): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
  pkuseg\inference.cpp(26222): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
  c:\users\jiebrother\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(551): note: see declaration of 'PyUnicode_FromUnicode'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

pkuseg

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by dongrixinyu** [comment]
instead of pip source, try to pull Github latest branch and install.

**Comment by dongrixinyu** [comment]
#40
