### ISSUE TITLE
兼容控制台所默认输出的帮助信息

### ISSUE THREAD

**Issue by cxwithyxy** [dongrixinyu/JioNLP#51]
**描述该功能的用处，可以提供相关资料描述该功能**
禁用默认的帮助信息输出功能, 如 jio.disable_help()

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
只要import 了, 控制台必然会输出
```
`jio.help()` is provided to search how to use jio functions.
Or browse `https://github.com/dongrixinyu/JioNLP` to get help.
```
每次都输出这一行呢, 感觉没法让我通过命令行调用的方式和其他非python的程序拼接起来

**Comment by dongrixinyu** [comment]
没明白什么意思：“和其他非python的程序拼接起来”

**Comment by cxwithyxy** [comment]
就是我用electronjs打包好的程序, 是通过命令行的方式和其他程序通讯的

**Comment by dongrixinyu** [comment]
这个只是打印了日志而已，而且是前台打印，没明白为何会影响到其它的程序
