### ISSUE TITLE
网页版的代码是不是可以开源

### ISSUE THREAD

**Issue by WangLaoShi** [dongrixinyu/JioNLP#52]
RT

**Comment by dongrixinyu** [comment]
网页版的 代码和 Git 基本同步，一般会领先于 pip 安装的版本。

**Comment by WangLaoShi** [comment]
你好，说的是，你的那部分网页，不是网页背后的代码。谢谢啦。

**Comment by dongrixinyu** [comment]
这个其实没必要哈。一个是前端这块本身不难，二一个是我写的前端代码也不好。网页前端代码github上有很多优秀项目，易用性非常好。
