### ISSUE TITLE
“中午”和“中午的”解析结果不一

### ISSUE THREAD

**Issue by sjk7524068** [dongrixinyu/JioNLP#54]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.7.4
- jionlp 版本: 1.3.53

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
from datetime import datetime


res = jio.parse_time('中午的两点一刻定一个闹铃', time_base=datetime.now())
print(res)
res = jio.parse_time('中午两点一刻定一个闹铃', time_base=datetime.now())
print(res)

```

3. 调用报错日志如下(Log):
```
> {'type': 'time_point', 'definition': 'accurate', 'time': ['2022-05-13 02:15:00', '2022-05-13 02:15:59']}
> {'type': 'time_point', 'definition': 'accurate', 'time': ['2022-05-13 14:15:00', '2022-05-13 14:15:59']}
```

**期望行为(Expectation)**

期盼返回结果是一致的, 但是两个返回结果不一

**请顺手 star 一下右上角的⭐小星星**

已⭐，大赞

**Comment by dongrixinyu** [comment]
这种应该使用
```
import jionlp as jio
jio.ner.extract_time('中午的两点一刻定一个闹铃')
```

- 使用建议：
- parse_time 是用来解析一个纯净准确的时间字符串的，比如“中午两点一刻”，不建议再带上下文其它信息。
- extract_time 首先抽取出时间字符串，然后再调用 parse_time 进行解析，解析前做了预处理，“的”这种词会被预处理掉。extract_time 的输入文本可以是一整段话，它会将其中所有的时间抽取出来。
- 由于上述都是采用规则来完成的，自然存在一些上下文应付不了的情况。
- 所以最建议的方式是，自行训练一个高质量的时间类别NER，然后对字符串做预处理，然后调用 parse_time进行解析。

**Comment by sjk7524068** [comment]
> 这种应该使用
> 
> ```
> import jionlp as jio
> jio.ner.extract_time('中午的两点一刻定一个闹铃')
> ```
> 
> * 使用建议：
> * parse_time 是用来解析一个纯净准确的时间字符串的，比如“中午两点一刻”，不建议再带上下文其它信息。
> * extract_time 首先抽取出时间字符串，然后再调用 parse_time 进行解析，解析前做了预处理，“的”这种词会被预处理掉。extract_time 的输入文本可以是一整段话，它会将其中所有的时间抽取出来。
> * 由于上述都是采用规则来完成的，自然存在一些上下文应付不了的情况。
> * 所以最建议的方式是，自行训练一个高质量的时间类别NER，然后对字符串做预处理，然后调用 parse_time进行解析。

感谢这么详细的回复，开始尝试用ner解析，有利有弊吧，ner解析出来的结果里包含了多个时间结果，需要做相应的一些处理
