### ISSUE TITLE
[技术咨询]jio.recognize_location(sent)

### ISSUE THREAD

**Issue by jamestch** [dongrixinyu/JioNLP#57]
**咨询的功能模块**
- 新闻地名识别：jio.recognize_location(text)

**咨询的具体内容和问题**
- 调用jio.recognize_location时需要下载https://github.com/explosion/spacy-pkuseg/releases/download/v0.0.26/spacy_ontonotes.zip，但国内经常超时失败。请问能提供国内镜像或者提供离线手动下载spacy_ontonotes.zip文件后怎么使用的方法吗？万分感谢！

**Comment by dongrixinyu** [comment]
这个属于spacy-pkuseg 这个包 的管理范畴了。建议可以多试几次，国内网络对github限速了。最好是能够有个vpn 哈。
