### ISSUE TITLE
{"code":11200,"message":"licc failed","sid":"its00082ab4@dx17569fccb5ba11d902"}

### ISSUE THREAD

**Issue by gitofding** [dongrixinyu/JioNLP#6]
{"code":11200,"message":"licc failed","sid":"its00082ab4@dx17569fccb5ba11d902"} 这是什么问题，怎么解决啊

**Comment by dongrixinyu** [comment]
请把问题说清楚

**Comment by gitofding** [comment]
谢谢，我也不知道是什么问题，现在已经不报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongrixinyu/JioNLP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 中午11:17
收件人:&nbsp;"dongrixinyu/JioNLP"<JioNLP@noreply.github.com&gt;;
抄送:&nbsp;"佐捷"<2891495739@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dongrixinyu/JioNLP] {"code":11200,"message":"licc failed","sid":"its00082ab4@dx17569fccb5ba11d902"} (#6)





 
请把问题说清楚

**Comment by dongrixinyu** [comment]
None
