### ISSUE TITLE
昨天、今天、明天识别结果类型是accurate

### ISSUE THREAD

**Issue by chaoxu1203** [dongrixinyu/JioNLP#60]
描述(Description)
1. 版本(Version):
pyhton: 3.7
jionlp: 1.3.58

2. jionlp的调用代码与输入文本(Code & Text):
jionlp.ner.extract_time('今天天气怎么样')

3. 解析结果：
[{'text': '今天', 'offset': [0, 2], 'type': 'time_point', 'detail': {'type': 'time_point', 'definition': 'accurate', 'time': ['2022-06-13 00:00:00', '2022-06-13 23:59:59']}}]

4. 期望结果
期望'今天'的解析结果类型definition是blur。在不同时间调用，结果中的'今天'解析得到的时间是不一样的，所以'今天'应该是一个模糊的时间。
同时，'本周'，'上周'，'本月'等表述的解析结果类型，也是blur。昨天、今天、明天，应该跟它们是同样的类型。

**Comment by dongrixinyu** [comment]
这样设计结果的原因是人对就近的时间，较短的时间比较敏感，对远的时间，长的时间感到模糊。所以，一天相对来讲是要给敏感的短时，所以设计为  accurate，一周以上就变得模糊。比如，你会记得昨天吃的什么饭，但是已经记不清上周吃的什么。这个是个相对的概念。

所以，请描述一下，在你的应用中，这样的解析结果产生了怎样的错误和矛盾。给一个具体的例子阐述一下
