### ISSUE TITLE
jio.summary.extract_summary 接口无效

### ISSUE THREAD

**Issue by zhangqianYY** [dongrixinyu/JioNLP#65]
pip 安装jionlp 1.4.7版本，按照这个[例子](https://github.com/dongrixinyu/JioNLP/wiki/Gadget-%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3#extract_summary)抽取文本摘要：
输入：
text = '海外网11月10日电当地时间9日，美国总统特朗普在推特上发文表示，美国国防部长马克·埃斯珀已经被开除。...' 
提取摘要之后输出和示例不同，实际输出为：
“海外网11月10日电当地时间9日，美国总统特朗普在推特上发文表示，美国国防部长马克·埃斯珀已经被开除。...”

**Comment by zhangqianYY** [comment]
请问是什么原因呢？ @dongrixinyu

**Comment by zhangqianYY** [comment]
`import jionlp as jio
text = '海外网11月10日电当地时间9日，美国总统特朗普在推特上发文表示，美国国防部长马克·埃斯珀已经被开除。...'

summary = jio.summary.extract_summary(text)
print(summary)

#海外网11月10日电当地时间9日，美国总统特朗普在推特上发文表示，美国国防部长马克·埃斯珀已经被开除。...
`
@dongrixinyu

**Comment by dongrixinyu** [comment]
自己看一下实现原理，文档里有
