### ISSUE TITLE
增加人名的识别

### ISSUE THREAD

**Issue by xxllp** [dongrixinyu/JioNLP#66]
**描述该功能的用处，可以提供相关资料描述该功能**
 识别文本中的人名等实体
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
人名只能用 NER 模型来搞，不适合本工具包完成。本工具包主要完成数据预处理与解析。
