### ISSUE TITLE
部分地址解析错误

### ISSUE THREAD

**Issue by maglev2007** [dongrixinyu/JioNLP#70]
python 版本 3.9
jionlu版本1.4.7

调用dict(jio.parse_location(strAdd, town_village=True))时出现部分地址解析错误，主要为：1.东兴市北仑大道59号，full_location解析结果为：四川省内江市东兴区市北仑大道59号。东兴市为广西防城港的市，结果却出现到了四川，而且市也错乱了。; 2.北海市重庆路其仓11号,full_location解析结果为：重庆市路其仓11号，错把路解析为市。

**Comment by dongrixinyu** [comment]
已修复
