### ISSUE TITLE
在docker镜像中部署的时候偶尔会报错

### ISSUE THREAD

**Issue by Pobby321** [dongrixinyu/JioNLP#72]
**描述(Description)**
在docker镜像中部署的时候导入jionlp包偶尔会报错
> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.7.11
- jionlp 版本: 1.3.34

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
```

3. 调用报错日志如下(Log):
```
File "/usr/local/lib/python3.7/site-packages/jionlp/__init__.py", line 19, in <module>
logging = set_logger('INFO')
File "/usr/local/lib/python3.7/site-packages/jionlp/util/logger.py", line 47, in set_logger
os.makedirs(filename_directory)
File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)

File exists: '/root/.jio_nlp_logs'
```

**期望行为(Expectation)**
希望能正常返回

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
`File exists: '/root/.jio_nlp_logs'`
这说明docker 内部有一个这样的文件了，
`ls -lth /root/.jio_nlp_logs` 看看呢

**Comment by Pobby321** [comment]
> `File exists: '/root/.jio_nlp_logs'` 这说明docker 内部有一个这样的文件了， `ls -lth /root/.jio_nlp_logs` 看看呢

**Comment by Pobby321** [comment]
> `File exists: '/root/.jio_nlp_logs'` 这说明docker 内部有一个这样的文件了， `ls -lth /root/.jio_nlp_logs` 看看呢

已经找到问题了谢谢，在多线程时，两个服务有一定概率会同时去创建这个文件，导致报错

**Comment by dongrixinyu** [comment]
可以参考说明文档，把logging 输出关闭掉，在`日志`部分的文档里有说明。

**Comment by Pobby321** [comment]
> 可以参考说明文档，把logging 输出关闭掉，在`日志`部分的文档里有说明。

谢谢！
