### ISSUE TITLE
身份证号码提取有一定的不准确的地方

### ISSUE THREAD

**Issue by jing86736238** [dongrixinyu/JioNLP#77]
**描述(Description)**
身份证号码提取对于月份的天数没有很好识别，天数不正确应该是不合理的身份证号
1. 版本(Version):
- python 版本: 3.9
- jionlp 版本: 1.4.14

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
text = '61123318970231123X'
res = jio.parse_time(text)
print(res)
```
返回了 ['61123318970231123X']

**期望行为(Expectation)**
应该为[]

要知道 2月是没有31号的 同样4月31号同样没有问题

**Comment by dongrixinyu** [comment]
这个号码是真实文本中存在过的？还是手工编辑测试的

**Comment by jing86736238** [comment]
> 这个号码是真实文本中存在过的？还是手工编辑测试的

手工编辑测试的。
