### ISSUE TITLE
我要使用Pyinstaller打包，请问 \dictionary 要怎么打包进去？

### ISSUE THREAD

**Issue by braveru** [dongrixinyu/JioNLP#78]
我要使用Pyinstaller打包，请问 \dictionary 要怎么打包进去？设置了参数，但是Jio还是找原来的路径。。。

**Comment by braveru** [comment]
不好意思，成功了，谢谢。

**Comment by braveru** [comment]
未成功。。。

**Comment by dongrixinyu** [comment]
这个 issue 已经并非 jionlp 项目本身。如果自己实在难以解决，可以找我付费有偿解决。

**Comment by braveru** [comment]
谢谢回复，我进去你的代码改了一下，现在解决了。
