### ISSUE TITLE
货币金额的不正当解析

### ISSUE THREAD

**Issue by zheyuye** [dongrixinyu/JioNLP#79]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.7.13
- jionlp 版本: 1.4.17

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
jio.ner.extract_money('-w', with_parsing=False)
print(res)
```

3. 调用报错日志如下(Log):
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/jionlp/algorithm/ner/money_extractor.py", line 172, in grid_search
    result = self.parse_money(clean_sub_string)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/jionlp/gadget/money_parser.py", line 571, in __call__
    money_string, default_unit=default_unit, ret_format=ret_format)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/jionlp/gadget/money_parser.py", line 639, in parse_single_money
    raise ValueError(self.type_error.format(money_string))
ValueError: the given money_string `-w` is illegal.

[]
```

**期望行为(Expectation)**

> 不希望有ValueError, 直接返回空值

**备注**

已验证4.1.7版本没有相关ValueError, 结果符合预期

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
这个不是 bug，而是多打印了一些异常日志。

**Comment by zheyuye** [comment]
首先感谢作者的回复, 也感谢提供了这么优秀的开源项目, 在`extract_money`函数中能看到返回的结果是“空值”, 这是符合预期的. 

但是我有几点疑虑想和您探讨一下: 
1. 从Error机制出发, 对于python的语言特性来说, raise Error仅在Python无法正常处理程序时才会发生一个异常, 也就是说Error意味着程序终止. 如果是一个符合预期的异常且有解决方案, 那可以用```try  ... except```的逻辑捕获, 并继续程序的运行. 而在这个case当中, `MoneyParser`中raise了相关的Error, 并且在`MoneyExtractor`的[grid_search函数中](https://github.com/dongrixinyu/JioNLP/blob/master/jionlp/algorithm/ner/money_extractor.py#L180-L182)做了捕获处理并输出日志. 实际上是, 这应该是`extract_money`运行时的工作日志, 而非**异常日志**, 因为并没有真正的终止程序. 换言之这样强硬的兜底式Error处理方式, 也不是妥善的方式. 细致的方案可能会是对于不同的Error给出不同的except方案, 这个case中`MoneyParser`内部的error在`MoneyExtractor`没有引发致命错误应当给出更加具体的方案.

2. 从使用者的角度出发, 他们并不关心模块的内部调用链路, 更不关心内部的工作日志, 对于调用结构更为复杂的外部模块来说更加如此. 这样的直接在 console print而不是写本地log的机制, 会不会在一定程度上让console信息变得更加凌乱, 很容易让使用者误解为程序以及终止运行了.

从我的拙见来看, 这边能想到一些改进思路:
1. 移除这部分的“异常日志”, 在debug模式下显式显示, 其他log模式正常.
2. 在`grid_search`函数中使用`MoneyExtractor`时, 对于致命错误raise Error并终止程序, 其他不影响程序继续运行的情况做except处理后在log进行记录.

**Comment by dongrixinyu** [comment]
多谢建议，目前就是这么做的，有 print_exception 参数控制异常打印。

MoneyParser 是金额解析器，MoneyExtractor 是抽取器。对于很多字符串，可能被抽取，但是无法被正确解析，这个时候会抛出异常。这个异常并非程序异常，而是告知用户输入的字符串不合规。

告知用户输入字符串不合规也可以用返回码来完成，也可以用 raise 来完成。只是我这里直接返回了 ValueError，其实更好的做法是自定义 Error 类型，帮助用户判断究竟是哪种情况造成的无法解析。
