### ISSUE TITLE
JIOJIO分词：语句中存在18位数字会报错

### ISSUE THREAD

**Issue by xiaochenggui** [dongrixinyu/JioNLP#81]
语句中存在连续18位数字就会报错，17、19都不会

**Comment by xiaochenggui** [comment]
![image](https://user-images.githubusercontent.com/29224888/191877976-a28bee1f-3c6b-4fe9-a3b0-dc620117596d.png)

**Comment by dongrixinyu** [comment]
谢谢反馈，会尽快修复，可以关注一下[jiojio](https://github.com/dongrixinyu/jiojio)，数字是 任何随机都报错吗？

**Comment by dongrixinyu** [comment]
我试了一下没问题 jiojio  需更新至最新版本
提bug需要写清楚 version，具体的代码，报错日志以文字提交。

**Comment by xiaochenggui** [comment]
> 谢谢反馈，会尽快修复，可以关注一下[jiojio](https://github.com/dongrixinyu/jiojio)，数字是 任何随机都报错吗？



>我找一下那个数据，因为我本地试了之后，还用你在的网页也试了的！

**Comment by xiaochenggui** [comment]
我找一下那条数据，因为当时我用你网页也试了的！

**Comment by xiaochenggui** [comment]
测试数据：220283200604108013（大幅度）
上面这个数据就会报错，好像是身份证后面紧跟”（ “就会出现问题

**Comment by xiaochenggui** [comment]
测试数据：220283200604108013（大幅度）

上面这个数据就会报错！

**Comment by dongrixinyu** [comment]
已修复，jiojio 需要更新到 1.2.3
