### ISSUE TITLE
“十年内”的歧义处理

### ISSUE THREAD

**Issue by ybkun** [dongrixinyu/JioNLP#87]
“十年内实现产业升级” 可以理解为未来10年
“十年内倒闭的企业”  应理解为过去10年
TimeParser仅凭candidate提供的“十年内”不足以判断是过去还是未来，请问是否已有解决方案？
或者“xxx内”放弃解析为time_span，仅返回time_delta是否更合理？

**Comment by dongrixinyu** [comment]
问的非常好，我考虑过这个问题。这种已经涉及到了上下文。但是解析方法仅仅局限于时间字符串本身，所以在解析时是两难的，有歧义的。

所以这种时间短语一定有解析错误的情况。

最好的方法是，用一个语言模型，bert 之类，在前面加两个 mask，看看模型能帮你补全“未来”还是“过去”或者别的。
然后再解析。

**Comment by dongrixinyu** [comment]
其实还是很难，上下文依赖太长，“十年内实现产业升级” 这句完全可以理解为  过去十年完成了产业升级。
汉语本身就没有动词变位，所以汉语的歧义非常多，更依赖上下文。

**Comment by ybkun** [comment]
感谢回答，有思路了

**Comment by dongrixinyu** [comment]
> 感谢回答，有思路了

如果有验证可行的方法，可以反馈给我
