### ISSUE TITLE
解析地址的时候速度比较慢，请问如何提速？

### ISSUE THREAD

**Issue by erichuazhou** [dongrixinyu/JioNLP#89]
在直接使用res_address = jio.parse_location(text_address, change2new=True, town_village=True) 来解析地址的时候，速度比较慢。请问如何提速？谢谢。

**Comment by dongrixinyu** [comment]
第一次调用的时候都内置了初始化，所以第一次调用比较慢。如果后续调用依然觉得很慢，可以考虑使用numba ，cython ，ctypes 等加速手段
