### ISSUE TITLE
tag 转 entity

### ISSUE THREAD

**Issue by xxllp** [dongrixinyu/JioNLP#91]
这里面是否可以支持BIO 格式的数据  ，我看现在需要bioe才可以

**Comment by dongrixinyu** [comment]
当然可以考虑支持，只是我感觉意义不大。
如果涉及到 CRF层，那么 BIOES 标准更容易发挥 CRF 转移概率作用。
如果不涉及CRF，bio 和 其它标准都是几乎等效的。

所以，如果可以，全部转成 bioes

**Comment by xxllp** [comment]
我就是没找到现成的~

**Comment by dongrixinyu** [comment]
> 我就是没找到现成的~

 我的意思是，你可以写一个 提过来🤭
