### ISSUE TITLE
湖南省长沙市会被识别到湖南省长沙市长沙县

### ISSUE THREAD

**Issue by XavierWonderful** [dongrixinyu/JioNLP#93]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: (通过 `python` 可查)
- jionlp 版本: (通过 `jionlp.__version__` 可查)

2. jionlp的调用代码与输入文本(Code & Text):
```
xxxxxxxxxxxx
e.g.
import jionlp as jio
res = jio.parse_time('XXXX')
print(res)
```

3. 调用报错日志如下(Log):
```
xxxxxxxxxxxx
e.g.
trackback: XXXXXX
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
已修复，过后会更新到 pip

**Comment by XavierWonderful** [comment]
你好，是没更新到pip吗。
重新安装了jionlp-1.4.30版本，重新测试了下，依然会把湖南省长沙市识别为{
    "province":"湖南省",
    "city":"长沙市",
    "county":"长沙县",
    "detail":"市",
    "full_location":"湖南省长沙市长沙县市",
    "orig_location":"湖南省长沙市",
}
