### ISSUE TITLE
“西安交通大学”被错误识别定位到“吉林省辽源市”[BUG]

### ISSUE THREAD

**Issue by MingQian12** [dongrixinyu/JioNLP#97]
>>> res = jio.parse_location('西安交通大学')
>>> res
{'province': '吉林省', 'city': '辽源市', 'county': '西安区', 'detail': '交通大学', 'full_location': '吉林省辽源市西安区 交通大学', 'orig_location': '西安交通大学'}

**Comment by dongrixinyu** [comment]
已修复
